#!/usr/bin/python3

#  Decription
#  ===========
#  Script to run gzdoom with various configurations/wads. Selectable via dmenu

#  Author: Dmitry (http://dmi3.net)
#  Source: https://github.com/dima2/bin

#  Requirements
#  ============
#  sudo apt-get install gzdoom dmenu python3 python3-setuptools
#  sudo easy_install3 sh

#  Usage
#  =====
#  doom

#  Settings
#  ========
MAP_DIR = "/media/archive/games/doom/wads/maps/"
MOD_DIR = "/media/archive/games/doom/wads/mods/"
MODS = {
  "vanilla":"",
  "russian_overkill":"hires.pk3 bdlitev13gzdoomV2.pk3 RO_pb_2.1b.pk3 Moldova_pb_v1.1.pk3 regeneration2.wad",
  "brutal_doom":"hires.pk3 brutalv018a.pk3 regeneration2.wad",
}
PARAMS = "+set sv_jump 2 +set sv_crouch 2"
TIMELIMIT=20 #(minutes) set 0 to play infinitely! 

#  Code
#  ====
from sh import ls,dmenu,gzdoom,echo,touch,killall,notify_send
from time import sleep


mod=dmenu(echo("\n".join(MODS.keys())))
mods=MODS[str(mod)].replace(" "," "+MOD_DIR)
wad=MAP_DIR+str(dmenu(ls(MAP_DIR,"-1","-t")))

cmd=PARAMS+" -file "+mods+" "+wad
print(cmd)
touch(wad) #because we sort by last modified = first in menu

gzdoom(cmd, _bg=True)
if TIMELIMIT>0:
  sleep(TIMELIMIT*60)
  notify_send("You have 10 seconds to save!")
  sleep(10)
  killall("gzdoom")
