#!/bin/bash

#  Decription
#  ===========
#  Script to simply sync all changes into git repository with one line command. For example publish local changes to github.

#  Author: Dmitry (http://dmi3.net)
#  Source: https://github.com/dmi3/bin

#  Requirements
#  ============
#  sudo apt-get install git

#  Usage
#  =====
#  cd folder-with-your-project
#  git-sync

git pull
git add *
echo "Files in changelist:"
git diff --name-status
read -p "Commit message (or Ctrl+Z/Ctrl+C to cancel): " commit_message
git commit -a -m "$commit_message" && git push origin master