#!/bin/bash

#  Decription
#  ===========
#  Script to simply sync all changes into git repository with one line command. For example publish local changes to github.

#  Author: Dmitry (http://dmi3.net)
#  Source: https://github.com/dmi3/bin

#  Requirements
#  ============
#  sudo apt-get install git

#  Usage
#  =====
#  cd folder-with-your-project
#  git-sync # if you want sync all files
#  git-sync -u # if you want only sync files explicitly added via `git add filename`

git pull

if [[ $* == "-u" ]]; then
  echo "Ignoring new files"
  add_arg="-u"
else
  add_arg="-A"
fi

git add $add_arg
echo "Files in changelist:"
git diff --name-status HEAD
read -p "Commit message (or Ctrl+Z/Ctrl+C to cancel): " commit_message
git commit -a -m "$commit_message" && git push origin master