#!/usr/bin/python3

#  Decription
#  ===========
#  Mounts USB device, syncs new podcast in gpodder then umounts device

#  Author: Dmitry (http://dmi3.net)
#  Source: https://github.com/dima2/bin

#  Requirements
#  ============
#  sudo apt-get install python3
#  wget https://raw.github.com/dima2/bin/master/notify-append -P ~/bin && chmod +x ~/bin/notify-append

#  Usage
#  =====
#  set LABEL to label of your player filesystem (for example `SANSA CLIP` to find label type `ls -l /dev/disk/by-label/`)
#  run `itunec` when you want to sync
#  or
#  gpodder -> Podcasts -> Prefences -> Devices; set  Device type to `Filesystem-based` and `Mountpoint` path where device is mounted by default
#  gpodder -> Podcasts -> Prefences -> Edit config -> cmd_all_download_complete -> itunec

LABEL = "AUDIOS"

from sh import ls,Command,udisks,ErrorReturnCode_1,traceback,gpo,zenity

notifyAppend=Command("notify-append")
def notify(text):
	notifyAppend("Itunec",text)

try:
	#Find device by LABEL
	devices = ls("-l","/dev/disk/by-label/")
	device = next(x for x in devices if LABEL in x)
	devid = device.split("/")[-1]
	devpath = "/dev/"+devid.replace("\n","")

	#Mount device 
	mntmsg = udisks("--mount",devpath)
	wasmnt = "is mounted" in mntmsg
	if not wasmnt:
		notify(mntmsg)

	notify("Starting synchronization")
	gpo("sync")
	
	#Umount device
	if not wasmnt:
		mntmsg = udisks("--unmount",devpath)
		if mntmsg == "":
			zenity("--info","--text","Its now safe to remove "+LABEL)		
		else:
			notify(mntmsg)
	else:
		zenity("--info","--text","Sync done")

	
except StopIteration: 
	notify("Unable to find device "+LABEL)
except ErrorReturnCode_1:
	notify("Unable to mount device "+LABEL)
except:
	notify("Unknown problem during sync")
	traceback.print_exc()