#!/bin/bash

#  Decription
#  ===========
#  Script to set keyboard layout depending if its Apple or regular keyboard + some settings

#  Usage
#  =====
#  layoutset

# If Apple keyboard plugged in, swap left alt and win and put tilde back to left upper corner
if lsusb | grep Apple  > /dev/null; then
  setxkbmap -option 'altwin:swap_lalt_lwin'
  xmodmap -e "keycode 94 = grave asciitilde"
else
  setxkbmap -option -option altwin:left_meta_win
fi

# Disable insert
xmodmap -e "keycode 118 ="

# Alt+Ctrl+Backspace restart, no caps lock, toggle via alt+shift
(setxkbmap lv && sleep 0.1s && setxkbmap -layout 'lv,ru' -option 'grp:alt_shift_toggle' -option 'terminate:ctrl_alt_bksp' -option 'ctrl:nocaps') &

# Unset caps is set previosly
xmodmap -e "clear lock" &
