#!/bin/bash

#  Decription
#  ----------
#  See <https://github.com/dmi3/bin/blob/master/poweroff>


setsid bash -c "sleep 3 && systemctl reboot"&
WIN_IDs=$(wmctrl -l | awk '{print $1}')
for i in $WIN_IDs; do wmctrl -ic "$i"  || true; done