#!/bin/bash
#Decrtiption
#===========
#Script to run append Skype messages in Notify OSD  as shown on http://thexnews.com/uploads/notify.gif
#Since x-canonical-append is broken in notify-send for example in Skype you will wait forever untill all messages are shown
#This script makes new messages readable in same notification window
#Readme in russian: http://thexnews.com/p/554

#Requirements
#============
#wget https://github.com/dima2/bin/blob/master/notify-append && chmod

#Usage: 
#======
#skypenotify "%sname" "%smessage"

focused_id=`xprop -root | grep "window id" | grep _NET_ACTIVE | cut -d " " -f 5 | cut -c 3-10`
app_id=`wmctrl -l | grep "$1" | cut -d " " -f 1 | cut -c 4-10`
if [[ $focused_id != $app_id ]]; then
  #If chat window not in focus send message
  notify-append "$1" "$2" "skype" &
fi

