#!/bin/bash

#  Decription
#  -----------
#  Script to change your terminal title to user@host when connecting to ssh and changing 
#  it back after exiting. Additionally sets green prompt on remote host.
#  Useful for Keepassx and visual distinction to avoid notorious "wrong window" problem.
#  Also works when connecting Fish → Bash
#
#  If you want hostname from local `~/.ssh/config` file to appear in title use [sssh2](https://github.com/dmi3/bin/blob/master/sssh2).

#  Author: [Dmitry](http://dmi3.net) [Source](https://github.com/dmi3/bin)

#  Requirements
#  ------------
#  `sudo apt-get install xdotool`

#  Usage
#  -----
#  `sssh user@hostname`
#  `alias ssh=sssh`

CUSTOM_PS1='PS1="\[$(tput bold)\]\[$(tput setaf 2)\][\u@\h \W]\\$ \[$(tput sgr0)\]"'
CUSTOM_TITLE='echo -e "\033]0;🖧 $USER@$HOSTNAME\a"'

PREV_TITLE=`xdotool getwindowfocus getwindowname`
/usr/bin/ssh -t "$@" "export PROMPT_COMMAND='eval '\\''$CUSTOM_TITLE;$CUSTOM_PS1'\\'; bash --login"
echo -e "\033]0;$PREV_TITLE\a"
