#!/bin/bash

#  Decription
#  -----------
#  Simple timer with sound and dialog window notification. To remind you to turn stove off :). 
#  Replace pc_up.wav to any available audiofile. 

#  Requirements
#  ------------
#      sudo apt-get install dunst aplay

#  Usage
#  -----
#      timer 6 # i.e. notify after 6 minutes

echo "$(date +"%H:%M") Will notify you in $1 minutes!"
sleep $1m && (notify-send -u critical "Timer done $1" & aplay ~/git/stuff/documents/sounds/pc_up.wav) &

# Alternative approach - show popup instead of notification
#sleep $1m && (zenity --info --text "Timer done" & cvlc /home/edmnovi/gitstuff/documents/sounds/pc_up_beep.wav vlc://quit) &

