#!/bin/bash

#  Decription
#  -----------
#  Simple timer with sound and dialog window notification. To remind you to turn stove off :). 
#  Replace pc_up.wav to any available audiofile. 

#  Requirements
#  ------------
#      sudo apt-get install zenity vlc

#  Usage
#  -----
#      timer 6 # i.e. notify after 6 minutes

sleep $1m && (zenity --info --text "Timer done" & vlc -q --no-repeat --play-and-exit -I dummy /home/graf/documents/sounds/quake/pc_up.wav) &

