#!/bin/bash

#  Decription
#  -----------
#  Script to control audio volume from console, hotkeys, e.t.c. Also shows nice Notify OSD buble with current volume value

#  Author: [Dmitry](http://dmi3.net) [Source](https://github.com/dmi3/bin)
  
#  Requirements
#  ------------
#      sudo apt-get install pulseaudio notify-osd
  
#  Usage
#  -----
#      volume (up|down|mute)

DEVICE_ID=$(cat ~/.config/pulse/*default-sink)

icon=notification-audio-volume-medium
if [[ $* == "down" ]]; then
  #amixer set PCM 5%-
  #amixer -q set Master 5- unmute
  pactl -- set-sink-volume $DEVICE_ID "-2%" &
  volume=$(pactl list sinks | grep Volume | grep -oe "[0-9]*%" | head -1)
elif [[ $* == "up" ]]; then
  #amixer set PCM 5%+
  #amixer -q set Master 5+ unmute
  pactl -- set-sink-volume $DEVICE_ID "+2%" &
  volume=$(pactl list sinks | grep Volume | grep -oe "[0-9]*%" | head -1)
elif [[ $* == "mute" ]]; then
  pactl set-sink-mute $DEVICE_ID toggle
  icon=notification-audio-volume-muted
  volume=0
fi

notify-send --hint string:x-canonical-private-synchronous:true "Volume" -i $icon -h int:value:$volume

