#!/bin/bash

#  Decription
#  -----------
#  Script to control audio volume from console, hotkeys, e.t.c. Also shows nice Notify OSD buble with current volume value

#  Author: [Dmitry](http://dmi3.net) [Source](https://github.com/dmi3/bin)
  
#  Requirements
#  ------------
#      sudo apt-get install pulseaudio notify-osd
  
#  Usage
#  -----
#      volume (up|down|mute)

DEVICE_ID=$(cat ~/.config/pulse/*default-sink)

icon=notification-audio-volume-medium
if [[ $1 == "down" ]]; then
  #amixer set PCM 5%-
  #amixer -q set Master 5- unmute
  pactl -- set-sink-volume $DEVICE_ID "-2%" &

  # First string containing `Volume` after string containing $DEVICE_ID. Since PulseAudio 15 can be replaced by `pactl get-sink-volume $DEVICE_ID`
  volume=$(pactl list sinks | grep $DEVICE_ID -a10 | grep Volume | grep -oe "[0-9]*%" | head -1)
elif [[ $1 == "up" ]]; then
  #amixer set PCM 5%+
  #amixer -q set Master 5+ unmute
  pactl -- set-sink-volume $DEVICE_ID "+2%" &
  volume=$(pactl list sinks | grep $DEVICE_ID -a10 | grep Volume | grep -oe "[0-9]*%" | head -1)
elif [[ $1 == "mute" ]]; then
  pactl set-sink-mute $DEVICE_ID toggle
  icon=notification-audio-volume-muted
  volume=0
fi

if [[ $2 != "--quiet" ]]; then
  notify-send --hint string:x-canonical-private-synchronous:true "Volume $volume" -i $icon -h int:value:$volume
fi  

# https://github.com/dmi3/qmk_firmware/blob/master/keyboards/handwired/onekey/kb2040/kbecho.py
if type "kbecho.py" > /dev/null; then
  # $volume without trailing %
  kbecho.py p ${volume%?}
fi

